language: java
deploy:
  provider: releases
  api_key:
    secure: v3DPB207PGbxE3EVJ9wMsU4iXyTeYljrGvgsYviGqRi9s9J+PyCbaqLp7ZqhoIvVzR9gC+EwkYRh2kOY9lJzUZu/+ok2YcQ9DC6skeoOeGE5cDV3HudzjnaR9TcpzLpS04jKoBXdJB/zzG5wsF0teEtK2zLRtK+Tw+zTlK58Ddlgd32wgR2oxKx2dYC6Jk01L87XbkoMUvF9pypLOoyGpdw7fGAPqPT2pjkA7ToCptV28oe91Tjz03X4CviANMJfYJOqu+tsUKNkBJJWx6ERu+YlsBW1qyjebJ/1BrE52IQV/Wfp49+6JQzs9uYnGLsOGF0jJF7l979mrjZ/dsoxbAC3TXguMegwTxs9K5ldfz73jBxYlM6esGfPCgnzNBPtsyKzIhWW6T89i+Y6EuMr0QgI1+ncvt9m4pvKdGNI0IFK4/OBJHPKRF/g0V636hfiDFRu10ypig2UTeVSk3SbGNdx3W0ywjZrWzrfg4qqxbfbT15p3ABum6JwIsW7GIzPE+DshDWcBksC76Z2UVFFqZAw0N+77Jscuq9SlGsGZJiZooO6npRAMjA6DZAw0V7Finb87znjRuKp5fOTGIYbDLvymtvCJpL5XKUk1vQcl1amGe98w3gk90RiF6vzpllXeJryyIr3wnttRH6hvUJ+bjKr0J0hAB3mHUh28YsIR4c=
  file: target/Optimexam.jar
  on:
    repo: sultanskyman/Optimexam
